### ISSUE TITLE
Old migration files throw errors

### ISSUE THREAD

**Issue by onemanstartup** [nullobject/rein#22]
I have old migrations with add_foreign_key and with `rein` they are throwing when I recreating database. I can't understand what causing this.
```
-- add_foreign_key("trades", "users", {:column=>"buyer_id"})
rails aborted!
ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column "user_id" referenced in foreign key constraint does not exist
: ALTER TABLE trades ADD CONSTRAINT trades_user_id_fk FOREIGN KEY (user_id) REFERENCES users (id)
```

**Comment by nullobject** [comment]
It looks like the `user_id` column is missing from your `trades` table at the time the `add_foreign_key` method is being run. Are you sure it's not missing, or hasn't been renamed? Maybe it's added in a later migration.

Sorry, I don't think this is a bug in rein.
