### ISSUE TITLE
Multi-column check constraints?

### ISSUE THREAD

**Issue by nileshtrivedi** [nullobject/rein#28]
ReadMe doesn't say anything about check constraints (Eg: Sender_Id cannot be the same as Receiver_Id) which are well-supported by Postgresql.

**Comment by nulty** [comment]
This is something that would interest me too. Has it been implemented/considered/planned?

**Comment by nullobject** [comment]
Thanks for the suggestion.

I'm planning on adding a `add_check_constraint` method which would allow you to specify an arbitrary postgresql check constraint. Like all the other methods in rein, it would just be syntactic sugar for adding the constraint manually.
