### ISSUE TITLE
Support table methods?

### ISSUE THREAD

**Issue by krainboltgreene** [nullobject/rein#33]
So it'd be neat to have (like the AR foreign_key constraint):

``` ruby
create_table :accounts do |table|
  table.string :email

  table.null_constraint :email, if: ...
end
```

I'll work on the PR if I get the greenlight.

**Comment by nullobject** [comment]
Hi @krainboltgreene, it would be interesting to see how this would work. What's your plan?

**Comment by nullobject** [comment]
I don't want rein too tightly coupled to the AR migrators, otherwise future versions of rails could break it.

**Comment by krainboltgreene** [comment]
Sadly, this feature is explicitly "write tightly coupled code that might break in future versions".

**Comment by nullobject** [comment]
Cool, thanks anyway 😄
