### ISSUE TITLE
I've used a reserved word for a column name and now I cannot create constraints :(

### ISSUE THREAD

**Issue by jgrau** [nullobject/rein#34]
In my application I've used the column name `from` (along with a `to` column) to represent the beginning and the end of an event. I haven't realized until now that `from` is a reserved word in postgres. That hasn't bitten me until now where I want to create a constraint on this column with

```
add_presence_constraint :blocked_periods, :from
```

I get

```
-- execute("ALTER TABLE blocked_periods ADD CONSTRAINT blocked_periods_from_presence CHECK ((from IS NOT NULL) AND (from !~ '^\\s*$'))")

rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::SyntaxError: ERROR:  syntax error at or near "from"
LINE 1: ... CONSTRAINT blocked_periods_from_presence CHECK ((from IS NO...
```

If I change the column name to eg `from_string` it works without problems. 

---

In an attempt to find a solution I changed your implementation of `contraint_name` in `util.rb`

```
      def self.constraint_name(table, attribute, suffix, options = {})
        options[:name].presence || "#{table}_#{attribute.delete("'")}_#{suffix}"
      end
```

And the migration

```
    add_presence_constraint :blocked_periods, "'from'"
```

And then the migration works

```
== 20180214083135 AddPresenceContraintsToBlockedPeriods: migrating ============
-- execute("ALTER TABLE blocked_periods ADD CONSTRAINT blocked_periods_from_presence CHECK (('from' IS NOT NULL) AND ('from' !~ '^\\s*$'))")
   -> 0.0082s
== 20180214083135 AddPresenceContraintsToBlockedPeriods: migrated (0.0084s) ===
```

---

I don't especially like that solution but it highlights a possible solution: wrapping all `attributes` in quotes. Would you accept a pull request that did that?

**Comment by nullobject** [comment]
HI @jgrau, thanks for pointing out the issue. It seems like wrapping the attributes in quotes sounds like a sensible solution. I'd definitely be interested in a PR for that 😜
