### ISSUE TITLE
Allow "NOT VALID" option

### ISSUE THREAD

**Issue by hlascelles** [nullobject/rein#47]
You can add constraints [without immediate validation](https://til.hashrocket.com/posts/86467be0b3-use-not-valid-to-immediately-enforce-a-constraint) using NOT VALID.

It would be great to have an option in `rein` like `not_valid: true`. Does that sound like something that would suit?

**Comment by nullobject** [comment]
Hi there @hlascelles, sorry for the delay I was away at a conference. That's a great suggestion, TIL about `NOT VALID`.

To me `not_valid: true` seems a little clunky. Perhaps it could be a little more user-friendly, for example something like `deferred: true`, or `check_existing_rows: false`.

What do you reckon?

**Comment by hlascelles** [comment]
Yes, I agree, that does look more intuitive. `NOT VALID` isn't very clear in the first place! 

`check_existing_rows: false` sounds good. I'll look at a PR when I get a moment...

**Comment by joehorsnell** [comment]
I suggest maybe `validate: false` would be a better name, since the command to validate the constraint is `alter table ... validate constraint ...`?

**Comment by ankane** [comment]
Rails use `validate: false` with foreign keys, so agree that may be a better name.

```ruby
add_foreign_key :users, :orders, validate: false
```
