### ISSUE TITLE
How to add presence constraint to a table with already data in it?

### ISSUE THREAD

**Issue by msdundar** [nullobject/rein#48]
Hi,

I'm trying to do two things in a migration:

1) Add a new column to a table,
2) Then add a presence constraint to the newly added column.

```ruby
class AddAdditionalFieldsToCountries < ActiveRecord::Migration[6.0]
  def change
    add_column :countries, :continent, :string
    add_presence_constraint :countries, :continent
  end
end
```

This table has already records in it. therefore my constraint throws an error:

```
PG::CheckViolation: ERROR:  check constraint "countries_continent_presence" is violated by some row
```

I believe that, there must be an option, such as, 'skip checking already existing data'. AFAIK there are some options in SQL such as `WITH CHECK | WITH NOCHECK`, however the documentation doesn't specify this case.

**Comment by nullobject** [comment]
Hi @msdundar, thanks for your comment.

What would be the use case for adding a constraint without enforcing it for existing data? Couldn't you run a migration to address the problems with your data _before_ you add a constraint?

I don't think postgres even supports the `NOCHECK` option anymore (as of 9.4).

**Comment by msdundar** [comment]
I followed these steps:

    Add column -> Add constraint -> Fix data issues

Then the follow order seems like this:

    Add column -> Fix data issues -> Add constraint

I think I got the point, thanks for your response :+1:

**Comment by nullobject** [comment]
No worries 👍
